// <auto-generated />
using System;
using FizzLigaQuiz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FizzLigaQuiz.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260326073144_InitQuiz")]
    partial class InitQuiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FizzLigaQuiz.Models.Kerdes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HelyesValasz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kategoria")
                        .HasColumnType("longtext");

                    b.Property<string>("KerdesSzoveg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LetrehozasDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nehezseg")
                        .HasColumnType("longtext");

                    b.Property<string>("ValaszA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValaszB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValaszC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValaszD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kerdesek");
                });

            modelBuilder.Entity("FizzLigaQuiz.Models.NapiQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KerdesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Datum")
                        .IsUnique();

                    b.HasIndex("KerdesId");

                    b.ToTable("NapiQuizok");
                });

            modelBuilder.Entity("FizzLigaQuiz.Models.QuizValasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FelhasznaloNev")
                        .HasColumnType("longtext");

                    b.Property<bool>("Helyes")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KerdesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValaszDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValasztottValasz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("QuizValaszok");
                });

            modelBuilder.Entity("FizzLigaQuiz.Models.NapiQuiz", b =>
                {
                    b.HasOne("FizzLigaQuiz.Models.Kerdes", "Kerdes")
                        .WithMany()
                        .HasForeignKey("KerdesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kerdes");
                });
#pragma warning restore 612, 618
        }
    }
}
